services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: car
      POSTGRES_USER: car
      POSTGRES_PASSWORD: car
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: